### ISSUE TITLE
tfenv fails on WSL / bash 5.0.7 if no keybase is present

### ISSUE THREAD

**Issue by mkielar** [tfutils/tfenv#117]
```
→ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)

→ tfenv --version
tfenv 1.0.1
```
It seems there is an issue with using `set -e` and failing subshells in `tfenv-install`. I don't have `keybase` or `shashum` present on my system, and executing tfenv fails with `exit code: 1` when trying to install terraform. See full log below.

Full log:
```
20:19 ● ~
→ TFENV_DEBUG=true tfenv install 0.12.3
+ [tfenv:22] '[' -z '' ']'
++++ [tfenv:23] readlink_f /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
++++ [tfenv:10] local target_file=/mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
++++ [tfenv:11] local file_name
++++ [tfenv:13] '[' /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv '!=' '' ']'
+++++ [tfenv:14] dirname /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
++++ [tfenv:14] cd /mnt/c/tools/wsl/home/marcin/.tfenv/bin
+++++ [tfenv:15] basename /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
++++ [tfenv:15] file_name=tfenv
+++++ [tfenv:16] readlink tfenv
++++ [tfenv:16] target_file=
++++ [tfenv:13] '[' '' '!=' '' ']'
+++++ [tfenv:19] pwd -P
++++ [tfenv:19] echo /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
+++ [tfenv:23] dirname /mnt/c/tools/wsl/home/marcin/.tfenv/bin/tfenv
++ [tfenv:23] cd /mnt/c/tools/wsl/home/marcin/.tfenv/bin/..
++ [tfenv:23] pwd
+ [tfenv:23] TFENV_ROOT=/mnt/c/tools/wsl/home/marcin/.tfenv
+ [tfenv:27] export TFENV_ROOT
+ [tfenv:28] PATH='/mnt/c/tools/wsl/home/marcin/.tfenv/libexec:/mnt/c/tools/wsl/home/marcin/.tfenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Users/marcin/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/marcin/AppData/Local/Programs/Python/Python37/:/mnt/c/Python37/Scripts/:/mnt/c/Python37/:/mnt/c/Python36/Scripts/:/mnt/c/Python36/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program Files/Crucial/Crucial Storage Executive:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/ProgramData/nvm::/mnt/c/Program Files/Java/jdk-9.0.1/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/ProgramData/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Program Files/Amazon/AWSCLI/:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/go/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/Bazaar:/mnt/c/Users/marcin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/marcin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/marcin/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Program Files/Oracle/VirtualBox:/mnt/c/Program Files/kdiff3:/mnt/d/go/bin:/mnt/c/tools/wsl/home/marcin/:.:/mnt/c/tools/wsl/home/marcin/.bin/:/mnt/c/tools/wsl/home/marcin/bin/:/mnt/c/tools/wsl/home/marcin/.local/bin'
+ [tfenv:29] export PATH
+ [tfenv:30] export TFENV_DIR=/mnt/c/tools/wsl/home/marcin
+ [tfenv:30] TFENV_DIR=/mnt/c/tools/wsl/home/marcin
+ [tfenv:40] command=install
+ [tfenv:41] case "${command}" in
++ [tfenv:54] command -v tfenv-install
+ [tfenv:54] command_path=/mnt/c/tools/wsl/home/marcin/.tfenv/libexec/tfenv-install
+ [tfenv:55] '[' -z /mnt/c/tools/wsl/home/marcin/.tfenv/libexec/tfenv-install ']'
+ [tfenv:60] shift 1
+ [tfenv:61] exec /mnt/c/tools/wsl/home/marcin/.tfenv/libexec/tfenv-install 0.12.3
+ [tfenv-install:3] '[' -n true ']'
+ [tfenv-install:3] set -x
+ [tfenv-install:4] source /mnt/c/tools/wsl/home/marcin/.tfenv/libexec/helpers
+ [tfenv-install:6] '[' 1 -gt 1 ']'
+ [tfenv-install:8] declare version_requested version regex
+ [tfenv-install:10] '[' -z 0.12.3 ']'
+ [tfenv-install:16] version_requested=0.12.3
+ [tfenv-install:19] [[ 0.12.3 =~ ^min-required$ ]]
+ [tfenv-install:31] [[ 0.12.3 =~ ^latest:.*$ ]]
+ [tfenv-install:34] [[ 0.12.3 =~ ^latest$ ]]
+ [tfenv-install:38] version=0.12.3
+ [tfenv-install:39] regex='^0.12.3$'
+ [tfenv-install:42] '[' -n 0.12.3 ']'
++ [tfenv-install:43] tfenv-list-remote
++ [tfenv-install:43] grep -e '^0.12.3$'
++ [tfenv-install:43] head -n 1
+ [tfenv-list-remote:2] set -e
+ [tfenv-list-remote:3] '[' -n true ']'
+ [tfenv-list-remote:3] set -x
+ [tfenv-list-remote:4] source /mnt/c/tools/wsl/home/marcin/.tfenv/libexec/helpers
+ [tfenv-list-remote:6] '[' 0 -ne 0 ']'
+ [tfenv-list-remote:12] grep -o -E '[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta|alpha)[0-9]+)?'
+ [tfenv-list-remote:13] uniq
+ [tfenv-list-remote:11] curlw -sf https://releases.hashicorp.com/terraform/
+ [helpers:18] local TLS_OPT=--tlsv1.2
++ [helpers:21] which sw_vers
+ [helpers:21] [[ -n '' ]]
+ [helpers:25] curl --tlsv1.2 -sf https://releases.hashicorp.com/terraform/
+ [tfenv-install:43] version=0.12.3
+ [tfenv-install:44] '[' -n 0.12.3 ']'
+ [tfenv-install:46] dst_path=/mnt/c/tools/wsl/home/marcin/.tfenv/versions/0.12.3
+ [tfenv-install:47] '[' -f /mnt/c/tools/wsl/home/marcin/.tfenv/versions/0.12.3/terraform ']'
+ [tfenv-install:52] TFENV_ARCH=amd64
+ [tfenv-install:53] case "$(uname -s)" in
++ [tfenv-install:53] uname -s
+ [tfenv-install:67] os=linux_amd64
++ [tfenv-install:71] which keybase
+ [tfenv-install:71] keybase_bin=
```

**Comment by iamhsa** [comment]
@mkielar 
I've made some tests with same versions of bash and tfenv, and without keybase and shasum.
Here the result : 
```
$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ tfenv --version
tfenv 1.0.1

$ tfenv install 0.12.3
[INFO] Installing Terraform v0.12.3
[INFO] Downloading release tarball from https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
######################################################################################################################################################################################################## 100.0%
[INFO] Downloading SHA hash file from https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_SHA256SUMS
tfenv: tfenv-install: [WARN] No keybase install found, skipping OpenPGP signature verification
tfenv: tfenv-install: [WARN] No shasum tool available. Skipping SHA256 hash validation
Archive:  tfenv_download.r46Ee8/terraform_0.12.3_linux_amd64.zip
  inflating: /root/.tfenv/versions/0.12.3/terraform  
[INFO] Installation of terraform v0.12.3 successful
[INFO] Switching to v0.12.3
[INFO] Switching completed
```
As you see I cannot reproduce the issue.

As tfenv has dependencies, could you check some other versions  ?
```
$ which --version 
$ curl  --version 
$ unzip --version
``` 

Looking at your logs, I noticed that your are on Windows Subsystem Linux, could you confirm ?
If it's right, I think you could update the issue title.

**Comment by mkielar** [comment]
Hi,
yes, I'm on WSL using Fedora Remix (from here: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases)

Here are the versions:
```
→ which --version
GNU which v2.21, Copyright (C) 1999 - 2015 Carlo Wood.
GNU which comes with ABSOLUTELY NO WARRANTY;
This program is free software; your freedom to use, change
and distribute this program is protected by the GPL.

→ curl --version
curl 7.64.0 (x86_64-redhat-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.7/openssl/zlib nghttp2/1.38.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink

→ unzip --version
caution:  both -n and -o specified; ignoring -o
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.
...
```

**Comment by mkielar** [comment]
Also, a quick test to show you what's happening on my system:
```
→ x="$(exit 7)"; echo $?
7
```
That should be 0, and I have no clue why the error from subshell is propagated. But it is, and this is what (I think) breaks `tfenv` for me.

**Comment by mkielar** [comment]
Workaround:
It works for me, when I modify the two lines in `~/.tfenv/libexec/tfenv-install` to this:
```
keybase_bin="$(which keybase 2>/dev/null || true)"
shasum_bin="$(which shasum 2>/dev/null || true)"
```

**Comment by Zordrak** [comment]
Long term, I am looking to moving error handling to a bash logging library I put together. Until then it's preferable to keep the error handling consistent which for right now means `set -e` and failing where necessary.

I'm interested in making sure we fix this issue, but I need to reproduce it or prove the root cause. It does seem like the `which` dependency may be key to this problem. I've just merged #119 that removes which from the dependencies. Does this resolve the issue entirely for you or do problems remain in that case?

**Comment by iamhsa** [comment]
I have made some tests on WSL to try reproduce this case.
Here the results: 

| WSL Linux Distrib | Bash version |"tfenv install latest"  status |
|-------------------|--------------|--------------------------------|
| Ubuntu 18.4          | 4.4.18    | OK |
| Ubuntu 19.4          | 5.0.3     | OK |
| Debian 10            | 5.0.3     | OK |
| Fedora Remix for WSL | 5.0.7     | Not tested * |

I tested with tfenv installed in ~/.tfenv and in /mnt/c/tools/wsl/home/user/.tfenv : I can not reproduce the problem.

To be sure I tested with a Fedora Docker image (as it have bash 5.0.7), but it's also OK.

| Docker Image | Bash version |"tfenv install latest"  status |
|-------------------|--------------|--------------------------------|
| Fedora 30         | 5.0.7    | OK |
| Archlinux         | 5.0.7    | OK |

So may be it's an issue with the Fedora Remix Distrib, or maybe something wrong with your configuration ...

 
_*as it costs about ten dollars_

**Comment by mkielar** [comment]
Sorry. Vacation time.
You can get Fedore Remix for WSL for free from here: https://github.com/WhitewaterFoundry/Fedora-Remix-for-WSL/releases

I've tried today with empty home directory (no `.bashrc`, no `bash_profile`, etc) and it still fails.
I also created a simple test script that does this:

```
#!/usr/bin/env bash
set -e 

echo "test which"
keybase_bin="$(which keybase 2>/dev/null)" 

echo "test command"
keybase_bin="$(command -v keybase 2>/dev/null)" 

echo "done"
```

In any case it returns with err code `1` after first test. So it's not really tfenv issue, it's my config issue, but I have no clue what causes it. Anyway, I'm closing the ticket.

**Comment by mkielar** [comment]
OK. I think this script just fails everywhere.
What was really wrong is that I had some leftover stuff in my `.bashrc` from Cygwin times, and it was:
```
export SHELLOPTS
```
Removing that, fixed my issue.
